server:
  port: 8089

spring:
  profiles:
    active: dev
  application:
    name: podcast-ws

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/podcasts
    username: postgres
    password: postgres

mybatis:
  type-aliases-package: br.com.edivaldorsj.model
  type-handlers-package: br.com.edivaldorsj.mapper.typehandler
  mapper-locations: classpath*:**/mappers/*Mapper.xml