spring:
  profiles:
    active: dev
  application:
    name: catalogo-podcast-ws
    output:
      ansi:
        enabled: always

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogo_podcast
    username: postgres
    password: postgres

mybatis:
  type-aliases-package: br.com.edivaldorsj.model
  type-handlers-package: br.com.edivaldorsj.mapper.typehandler
  mapper-locations: classpath*:**/mappers/*Mapper.xml

logging:
  level:
    br.com.ithappens: ERROR